[workspace]
members = [
  "tasks",
  "taskmaster",
]
resolver = "2"

[profile.release]
strip = true
lto = true # Link Time Optimization
codegen-units = 1 # reduce parallelislm for more aggressive LTO 
opt-level = "s" # optimize for binary size

